version: "3.9"
services:
  frontend:
    image: ghcr.io/stjj-de/frontend:latest
    restart: always
    networks:
      default:
      caddy:
        aliases:
          - website2_frontend
    environment:
      INTERNAL_STRAPI_HOST: strapi:8000
    depends_on:
      - strapi

  strapi:
    image: ghcr.io/stjj-de/strapi:latest
    restart: always
    networks:
      default:
      caddy:
        aliases:
          - website_strapi
    environment:
      MYSQL_HOST: mariadb
      MYSQL_PORT: 3306
      MYSQL_USER: strapi
      MYSQL_DATABASE: strapi
    env_file:
      - ".env"
    volumes:
      - ./data/uploads:/app/public/uploads
      - /etc/timezone:/etc/timezone
    depends_on:
      - mariadb

  mariadb:
    image: "mariadb:latest"
    restart: always
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
    # ports:
      # - "127.0.0.1:3306:3306"
    env_file:
      - ".env"
    volumes:
      - "./data/mariadb:/var/lib/mysql"

networks:
  caddy:
    name: caddy
    external: true
