version: "3.9"
services:
  frontend:
    image: ghcr.io/stjj-de/frontend:latest
    restart: always
    networks:
      default:
      caddy:
        aliases:
          - website2_frontend
    environment:
      INTERNAL_STRAPI_HOST: strapi:8000
    depends_on:
      - strapi

  strapi:
    image: ghcr.io/stjj-de/strapi:latest
    restart: always
    networks:
      default:
      caddy:
        aliases:
          - website_strapi
    env_file:
      - ".env"
    volumes:
      - ./data/data.db:/app/data.db
      - ./data/uploads:/app/public/uploads
      - /etc/timezone:/etc/timezone

networks:
  caddy:
    name: caddy
    external: true
