version: "3"

services:
  frontend:
    image: "docker.pkg.github.com/stjj-de/frontend/frontend:latest"
    restart: always

    ports:
      - "3000:3000"

    environment:
      SSR_BACKEND_HOST: "backend:8000"

    depends_on:
      - backend

  backend:
    image: "docker.pkg.github.com/stjj-de/backend/backend:latest"
    restart: always

    ports:
      - "8000:8000"

    environment:
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      MARIADB_USER: backend
      MARIADB_DATABASE: stjj-de

    env_file:
      - "./backend.env"

    volumes:
      - ./data:/app/data

    depends_on:
      - mariadb

  mariadb:
    image: "mariadb:latest"
    restart: always

    ports:
      - "4000:3306"

    environment:
      MYSQL_DATABASE: stjj-de
      MYSQL_USER: backend

    env_file:
      - "./mariadb.env"
