version: "3"

services:
  frontend:
    image: "docker.pkg.github.com/stjj-de/frontend/frontend:latest"
    ports:
      - "3000:3000"

    environment:
      SSR_BACKEND_HOST: "backend:8000"

  depends_on:
    - backend

  backend:
    image: "docker.pkg.github.com/stjj-de/backend/backend:latest"
    ports:
      - "8000:8000"

    env_file:
      - "./backend.env"

    volumes:
      - ./data:/app/data
