version: "3"

services:
  frontend:
    image: "docker.pkg.github.com/stjj-de/frontend/frontend:latest"
    restart: always

    ports:
      - "127.0.0.1:3000:3000"

    environment:
      SSR_BACKEND_HOST: "backend:8000"

    depends_on:
      - backend

  backend:
    image: "docker.pkg.github.com/stjj-de/backend/backend:latest"
    restart: always

    ports:
      - "127.0.0.1:8000:8000"

    environment:
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      MARIADB_USER: backend
      MARIADB_DATABASE: stjj-de

    env_file:
      - "./backend.env"

    volumes:
      - ./data/backend:/app/data
      - /etc/timezone:/etc/timezone

    depends_on:
      - mariadb

  mariadb:
    image: "mariadb:latest"
    restart: always

    ports:
      - "127.0.0.1:3306:3306"

    environment:
      MYSQL_DATABASE: stjj-de
      MYSQL_USER: backend

    env_file:
      - "./mariadb.env"

    volumes:
      - "./data/db:/var/lib/mysql"
      
  ackee:
    image: electerious/ackee
    restart: always
    ports:
      - "127.0.0.1:4000:3000"
      
    environment:
      - WAIT_HOSTS=mongo:27017
      - ACKEE_MONGODB=mongodb://mongo:27017/ackee
      
    env_file:
      - "./ackee.env"
      
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/analytics:/data/db
