version: "3.9"
services:
  caddy:
    image: caddy:2.3.0-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static/Caddyfile:/etc/caddy/Caddyfile
      - ./data/data:/data
      - ./data/config:/config

networks:
  default:
    name: caddy
